---
title: "EDA"
author: "Kobe Sarausad"
date: "5/10/2023"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

data <- read.csv("data/31119913_National2020.csv")

cols <- str_split("age10
sex
educ18
income20
racism20
life
party
stanum
sizeplac
pres
weight
vote2016
votemeth
abortion
climatec", "\n")[[1]]

data_subset <- data %>% 
  select(cols)
```

# 
````{r rand_eda}
ggplot(data = data_subset) +
  geom_bar(mapping = aes(x = pres, fill = sex))

ggplot(data = data_subset) +
  geom_bar(mapping = aes(x = pres, fill = party))

ggplot(data = data_subset) +
  geom_bar(mapping = aes(x = pres, fill = sizeplac))

ggplot(data = data_subset) +
  geom_bar(mapping = aes(x = pres, fill = vote2016))

ggplot(data = data_subset) +
  geom_bar(mapping = aes(x = pres, fill = climatec))

ggplot(data = data_subset) +
  geom_boxplot(mapping = aes(x = pres, y = weight)) +
  scale_y_log10()
```

```{r prob_wts}
data_subset <- data_subset %>%
  mutate(prob_wts = weight / sum(weight))
```

